### ISSUE TITLE
Missing startupProbe causes container to enter reboot loop.

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [Part-DB/helm-charts#5]
From [template](https://github.com/Part-DB/helm-charts/blob/0071f0a598b7fe3e2764a7ec406c5ea3e31ce75a/charts/part-db/templates/statefulset.yaml#L74):

``` yaml
        livenessProbe:
          httpGet:
            path: /
            port: http
          timeoutSeconds: 5
```

A livenessProbe is defined, which is great.

However, if the application does not start.... in 5 seconds, this will cause the application to be killed.

```
│ [08-Mar-2025 18:08:13] NOTICE: fpm is running, pid 23                                                                                                                                                                                          
│ [08-Mar-2025 18:08:13] NOTICE: ready to handle connections                                                                                                                                                                                     
│ [08-Mar-2025 18:08:13] NOTICE: systemd monitor interval set to 10000ms                                                                                                                                                                         
│ [Sat Mar 08 18:08:13.856143 2025] [mpm_event:notice] [pid 1:tid 1] AH00489: Apache/2.4.62 (Debian) configured -- resuming normal operations                                                                                                    
│ [Sat Mar 08 18:08:13.856430 2025] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'                                                                                                                                   
│ [Sat Mar 08 18:08:20.855377 2025] [mpm_event:notice] [pid 1:tid 1] AH00492: caught SIGWINCH, shutting down gracefully                                                                                                                          
│ - -  08/Mar/2025:18:08:15 +0000 "GET /index.php" 302                                                                                                                                                                                           
│ 10.42.4.1 - - [08/Mar/2025:18:08:15 +0000] "GET / HTTP/1.1" 302 736 "-" "kube-probe/1.31"                                                                                                                                                      
│ stream closed EOF for part-db/parts-db-part-db-0 (part-db)    
```

This was identified on a fresh install of the chart. 

Adding a simple startup probe, should resolve this issue.

Relevant Documentation: 

- https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

Will test.

**Comment by XtremeOwnageDotCom** [comment]
Using this kustomizations, to add a startupProbe-

``` yaml
patchesStrategicMerge:
  - startupProbe.yaml
```

``` yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: parts-db-part-db
spec:
  template:
    spec:
      containers:
        - name: part-db
          startupProbe:
            tcpSocket:
              port: 80
            failureThreshold: 30
            periodSeconds: 10
```

Yields these results on a fresh install.

![Image](https://github.com/user-attachments/assets/c1a435d5-7c74-4039-b8d7-d2fa56793bd1)

Without this kustomization, these results are yielded:

![Image](https://github.com/user-attachments/assets/5717bf26-5de7-4117-97bf-ceb0b1441aa3)

![Image](https://github.com/user-attachments/assets/44461dd7-5ddb-4e4b-96d3-1acfcb660a57)

Shall create PR shortly.
