### ISSUE TITLE
DATABASE_URL does not resolve correctly with custom database type

### ISSUE THREAD

**Issue by netthier** [Part-DB/helm-charts#7]
If I set `db.type` to postgresql, the chart will template its env secret like this:
```yaml
DATABASE_URL: $(DB_TYPE)://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOSTNAME)/$(DB_DATABASE
)
DB_DATABASE: app
DB_HOSTNAME: partdb-db-rw:5432
DB_PASSWORD: hunter2
DB_TYPE: postgresql
```
However, Kubernetes requires dependent env variables to be defined explicitly after its dependencies are defined.
`DATABASE_URL` remains unexpanded even if the `DB_` vars are set, preventing the pod from starting successfully.
Adding
```yaml
extraVars:
  - name: DATABASE_URL
    value: "$(DB_TYPE)://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOSTNAME)/$(DB_DATABASE)"
```
to the values fixes this issue.
I'd assume `MAILER_DSN` is affected by the same issue.
